# Generated by Django 5.1.1 on 2024-10-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rental_rented_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='rented_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
